# Change these first
owner: jacksonp2008 # Your GitHub organization or username, where this repository lives
repo: nayauptime # The name of this repository

sites:
  - name: Naya Pilates Main
    url: https://nayapilates.com/
  - name: Naya Members
    url: https://nayapilates.com/memberships/
  - name: Naya Courses
    url: https://nayapilates.com/courses/
  - name: Naya Coaching
    url: https://nayapilates.com/coaching/
  - name: Naya Podcasts
    url: https://nayapilates.com/podcasts/
  - name: Bearclaw Finder
    url: https://movewith.site/bearclaws/
  - name: Recipe Site
    url: https://movewith.site/imhungry/
  - name: Binford Estates
    url: https://www.movewith.site/binford/
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: nayapilates.com
  baseUrl: /jacksonp2008
  logoUrl: https://i0.wp.com/nayapilates.com/wp-content/uploads/2024/01/SITE-LOGO-transparent.png?fit=100%2C101&ssl=1
  name: nayauptime
  introTitle: "Naya Monitor"
  introMessage: "Welcome"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
